const ORDER_TITLES = {
  OZONATION: "Ozonation",
  DRY_CLEANING: "Dry cleaning",
};

const ORDER_STATUS = {
  CREATED: "created",
  APPROVED: "approved",
  IN_PROGRESS: "in-progress",
  DONE: "done",
};

const CREATED_ORDERS_CHANNEL_ID = "-1002017671793";
const APPROVED_DRY_OZONATION_CHANNEL_ID = "-1002083170852";
const APPROVED_REGULAR_CHANNEL_ID = "-1002083336889";

module.exports = {
  ORDER_TITLES,
  ORDER_STATUS,
  CREATED_ORDERS_CHANNEL_ID,
  APPROVED_REGULAR_CHANNEL_ID,
  APPROVED_DRY_OZONATION_CHANNEL_ID,
};
